### ISSUE TITLE
Error tras actualizacion a 1.2.1

### ISSUE THREAD

**Issue by negutierrez** [open-source-uc/sincding#30]
- [x] Installed node with version >= 8 (`node -v`)
- [x] Checked other issues

### Describe your problem
Desde la actualizacion a 1.2.1 que no funciona el programa

### Attach log
Paste the full log when running `sincding sync`
```bash
#Paste log here

Your environment has been set up for using Node.js 6.10.3 (x64) and npm.

C:\Users\Nicolás>sincding
C:\Users\Nicolás\AppData\Roaming\npm\node_modules\sincding\src\index.js:75
sync = async data => {
             ^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)


```
PD: Muchas gracias por esto, me ayudo mucho el semestre pasado y encuentro que es una excelente idea!
Saludos

**Comment by negebauer** [comment]
@negutierrez como puedes ver aquí
```bash
Your environment has been set up for using Node.js 6.10.3 (x64) and npm.
```

Estás usando Node version 6.10.3
sincding ahora funciona con Node version >= 8

Tienes que actualizar la versión de Node para poder correr la versión más nueva

**Comment by negutierrez** [comment]
Acabo de notar eso, jaja, perdona.
Estoy actualizandolo ahora y lo pruebo.
Muchas gracias !

**Comment by negutierrez** [comment]
Ya actualicé y sincding corre bien, pero al sincronizar no descarga correctamente los archivos, y me tira error tipo:

```
--- 1.2.1 ERROR sync
      Request failed with status code 500

  If necessary, please report this problem here
    https://github.com/open-source-uc/sincding/issues
-----
```
He hecho "sync" varias veces y generalmente no encuentra todos los archivos al hacer el parsing por carpeta, y siempre falla al tratar de descargar algun archivo, aunque algunos los logra descargar y se cae después.
ojalá sirva mi descripción,
Saludos!

**Comment by negebauer** [comment]
Puedes probar con la 1.2.3 que subí hoy?

**Comment by negutierrez** [comment]
Hola, probé de nuevo y el error sigue, este es el log:
```
Your environment has been set up for using Node.js 8.2.1 (x64) and npm.

C:\Users\Nicolás>sincding
Welcome to sincding!
Version 1.2.3

Current user data
user: negutierrez
path: C:\Users\Nicolás\Desktop\Universidad 2017 - 2
ignore: IIC2413 ICS2123

Commands:
 - data: Update your user data
 - sync: Download sincding files
 - exit: Exit sincding
prompt: command: sync
Executing 'sync' command
Starting login
Checking login
Login correct
Getting courses list
Parsing courses list

Found courses
 - ICS2121 Métodos de Optimización
 - ICS2122 Taller de Investigación Operativa (Capstone)
 - IEE2473 Laboratorio de Electrónica Analógica y Digital
 - IIC2713 Sistemas de Información

Parsing Sistemas de Información
Parsing Taller de Investigación Operativa (Capstone)
Parsing Métodos de Optimización
Parsing Laboratorio de Electrónica Analógica y Digital
Parsing Material de clases
Parsing Sistemas de Información
Parsing Proyecto y Tareas
Parsing Temas-Clases
Parsing Tema00 Introducción
Parsing Tema01 Estudio de Casos
Parsing Tema02 Sistemas e Información

Found:

- Métodos de Optimización
  - folders: 1
  - files: 1

- Taller de Investigación Operativa (Capstone)
  - folders: 0
  - files: 0

- Laboratorio de Electrónica Analógica y Digital
  - folders: 0
  - files: 0

- Sistemas de Información
  - folders: 6
  - files: 10

Download:

- Métodos de Optimización
  - folders: 0
  - files: 0

- Taller de Investigación Operativa (Capstone)
  - folders: 0
  - files: 0

- Laboratorio de Electrónica Analógica y Digital
  - folders: 0
  - files: 0

- Sistemas de Información
  - folders: 0
  - files: 8

Creating missing folders...

Starting downloads, this may take a while...

--- 1.2.3 ERROR sync
      Request failed with status code 500

  If necessary, please report this problem here
    https://github.com/open-source-uc/sincding/issues
-----

```
Saludos!

**Comment by negebauer** [comment]
Subí una nueva versión `v1.2.5`
Puedes probarla?
`npm i -g sincding`

**Comment by negutierrez** [comment]
Hola, estoy probando nuevamente y generalmente en algún punto se cae al tratar de descargar (tirando el mismo error status code 500), pero no es tan terrible ya que corriendo varias veces el sync logra descargar todos los archivos

**Comment by negebauer** [comment]
Buena, acabo de agregarle que trate de hacer nuevo las descargas cuando tiran 500 en la `v1.2.6`

**Comment by negebauer** [comment]
@negutierrez puedes probarla y decirme que tal te funciona?

**Comment by negutierrez** [comment]
Hola!, lo acabo de revisar, con la versión 1.2.7 y anda perfecto, logra descargar todo sin ningún problema.
Muchas gracias por todo!

**Comment by negebauer** [comment]
Buena, de nada!
